FROM ubuntu:latest
LABEL maintainer="snowdream <Jianfei@hub.cn.com>"

# 设置时区为上海
RUN set -eu && \
    apt-get update && \
    apt-get install -y tzdata && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 安装必要的包
RUN apt-get update && \
    apt-get install -y bash inotify-tools curl unzip tar && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 创建工作目录
WORKDIR /app

# 下载并解压 Xray
# RUN curl -L -o xray.zip https://github.com/XTLS/Xray-core/releases/download/v1.8.23/Xray-linux-64.zip && \
#     unzip -o xray.zip && \
#     rm xray.zip

# 下载最新版本的 Xray
RUN curl -s https://api.github.com/repos/XTLS/Xray-core/releases/latest \
    | grep "browser_download_url.*Xray-linux-64.zip" \
    | cut -d '"' -f 4 \
    | xargs curl -L -o xray.zip && \
    unzip -o xray.zip && \
    rm xray.zip

# 复制 xray.sh 脚本到容器
COPY ./docker/xray.sh /app/

# 设置权限
RUN chmod +x /app/xray.sh /app/xray

# 设置环境变量
ENV PATH="/app:${PATH}"
ENV CONFIG_DIR="/app/config"
ENV LOG_FILE="/app/config/logfile.log"
ENV XRAY_EXEC="/app/xray"
ENV PID_FILE="/app/xray.pid"

# 运行脚本
# CMD ["/app/xray.sh"]
CMD ["xray.sh"]
