# 使用Alpine Linux作为基础镜像
FROM alpine:latest

# 维护者信息
LABEL maintainer="snowdream <1009721777@qq.com>"

# 环境变量
#ENV NGINX_VERSION=1.26.1

# 设置时区为上海
RUN set -eu && \
    apk add --no-cache tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    apk del tzdata


# 更新Alpine Linux的软件包索引并安装所需软件包
RUN set -eu && \
    apk update && \
    apk add --no-cache \
        nginx-mod-stream \
        tree \
        nano \
        iproute2 \
        iputils \
        tar

# 复制 tar 文件到容器中
COPY ./docker/nginx_configs.tar /etc/nginx/

# 解压缩 tar 文件到 /etc/nginx 目录中，并删除 tar 文件
RUN tar -xvf /etc/nginx/nginx_configs.tar -C /etc/nginx/ && rm /etc/nginx/nginx_configs.tar

# 暴露nginx的默认HTTP端口
EXPOSE 80
EXPOSE 443

# 启动nginx服务
CMD ["nginx", "-g", "daemon off;"]
