FROM alpine:latest

LABEL maintainer="snowdream <1009721777@qq.com>"

# 设置时区为上海
RUN set -eu && \
    apk add --no-cache tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    apk del tzdata

# 覆盖 /etc/apk/repositories 文件内容
RUN echo "http://dl-cdn.alpinelinux.org/alpine/latest-stable/main" | tee /etc/apk/repositories && \
    echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" | tee -a /etc/apk/repositories 

# 安装必要的软件
RUN set -eux && \
    apk update && \
    apk add --no-cache bash inotify-tools curl unzip tar

# 创建工作目录
WORKDIR /app

# 复制 tar 文件到容器中
COPY ./docker/nps_amd64_server.tar /app/

# 解压文件
RUN tar -xvf nps_amd64_server.tar && \
    rm nps_amd64_server.tar  # 解压后删除 tar 文件

# 设置执行权限
RUN chmod +x /app/nps

# 指定启动命令
CMD ["/app/nps"]
