FROM alpine:latest

LABEL maintainer="snowdream <1009721777@qq.com>"

# 覆盖 /etc/apk/repositories 文件内容
RUN echo "http://dl-cdn.alpinelinux.org/alpine/latest-stable/main" | tee /etc/apk/repositories && \
    echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" | tee -a /etc/apk/repositories 

# 设置时区为上海
RUN set -eu && \
    apk add --no-cache tzdata frp && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    apk del tzdata && \
    rm -rf /var/cache/apk/* && \
    rm -rf /etc/frp/frps.toml

COPY ./docker/frps.toml /etc/frp/

WORKDIR /etc/frp

# 指定启动命令
CMD ["frps"]
