FROM alpine:latest

LABEL maintainer="snowdream <1009721777@qq.com>"

# 设置时区为上海
RUN set -eu && \
    apk add --no-cache tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    apk del tzdata

# 覆盖 /etc/apk/repositories 文件内容
RUN echo "http://mirrors.nju.edu.cn/alpine/latest-stable/main" | tee /etc/apk/repositories && \
    echo "http://mirrors.nju.edu.cn/alpine/edge/community" | tee -a /etc/apk/repositories 

# 安装 frps
RUN set -eux \
    apk update \
    apk add --no-cache frp

WORKDIR /

# 指定启动命令
CMD ["frps", "-c", "/etc/frp/frps.toml"]
