# 使用Alpine Linux作为基础镜像
FROM alpine:latest

# 维护者信息
LABEL maintainer="snowdream <1009721777@qq.com>"

# 设置时区并安装必要的包
RUN apk update && \
    apk add --no-cache nginx-mod-stream tzdata python3 py3-watchdog py3-pip bash && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    apk del tzdata

WORKDIR /app

# 将监控脚本复制到镜像中
COPY ./docker/nginx.py /app/

# 确保脚本可执行
RUN chmod +x /app/nginx.py

# 设置环境变量
ENV PATH="/app:${PATH}"

# 启动监控和 Nginx
CMD ["python3", "nginx.py"]
