name: Build  Xray alpine Image

on:
  workflow_call:

jobs:
  push-Xray:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for Xray
        run: docker build -f ./docker/Dockerfile_Xray_alpine -t ${{ secrets.DOCKER_USERNAME }}/xray:alpine .

      - name: Push Docker image for Xray
        run: docker push ${{ secrets.DOCKER_USERNAME }}/xray:alpine
